
experiment:
  name: "Baseline 1"
  version: 1.0
  seed: 31
  description: "Fine-tuned ResNet-50 for Single-Frame Based Group Activity Recognition"

data:
  dataset_name: "Group Activity Dataset"
  dataset_path: "data"
  annot_path: "data/annot_all.pkl"
  videos_path: "data/videos"
  output_path: "modeling/outputs"

  video_splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    validation: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

  augmentation:
    random_flip: true

model:
  model_name: "Group Activity Classification"
  backbone_name: "ResNet50"
  num_classes: 8
  class_labels: ["r_set", "r_spike" , "r-pass", "r_winpoint", "l_winpoint", "l-pass", "l-spike", "l_set"]

training:
  optimizer: "AdamW"
  batch_size: 128
  num_epochs: 15
  learning_rate: 1e-3
  weight_decay: 1